
# `Deployment` for the mongodb server
#Container Port Chaged to 27017 from Null (mongodb-deployment)       [24/03/22]

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
          - containerPort: 27017
        env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mongo-root-password 

---
# `Deployment` for mongo-express
# Container Port Chaged to  8081 from Null (flask-app-deployment)   [24/03/22]

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: secret
                key: mongo-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: mongo-root-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: database_url
---
#`Deployment` for flask-app
# Container Port Chaged to 5001 from Null (flask-app-deployment)   [24/03/22]


apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: blogapp:1.0
        ports:
        - containerPort: 5001
        imagePullPolicy: Never
        env:
        - name: user
          valueFrom:
            secretKeyRef:
              name: secret
              key: mongo-root-username
        - name: password
          valueFrom:
            secretKeyRef:
              name: secret
              key: mongo-root-password 
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: database_url

# All cahnges are commented above update services.yaml and comment out the changes 