# Secret file Username and password which will be used in deployments file 

apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  mongo-root-username: <username>
  mongo-root-password: <username>
