# Secret file Username and password which will be used in deployments file 
# mongo db root user name and password are same no need to make any changes here

apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  mongo-root-username: cm9vdA==
  mongo-root-password: cm9vdA==